#!/usr/bin/with-contenv bash

echo "Closing out Plex Media Server."

if /usr/local/bin/home_persistent_mounted; then
  flock "$SYNC_STATUS_FILE" /usr/local/bin/sync_and_log "$HOME" "$HOME_PERSISTENT"
  git -C "$HOME_PERSISTENT" commit --amend --allow-empty -m "clean $(date)" &> /dev/null
fi
