#!/usr/bin/with-contenv bash

echo "Syncing config directory."
home="$(echo ~plex)"
status_file="/etc/services.d/plex/.syncing"

# Environment variable $SYNC-PERSISTENT must be set
if [ ! -z ${SYNC-PERSISTENT+x} ]; then
  flock -n "$status_file" rsync -av "$home/" "${home}-persistent"
  rm "$status_file"
fi
