#!/usr/bin/with-contenv bash

echo "Syncing config directory."

# Environment variable $SYNC_PERSISTENT must be set
if [ ! -z ${SYNC_PERSISTENT+x} ]; then
  flock -n "$SYNC_STATUS_FILE" rsync -av "$HOME/" "$HOME_PERSISTENT"
  rm "$SYNC_STATUS_FILE"
fi
